---
name: 'Generic PANOPTES Unit'
location:
    name: Mauna Loa Observatory
    latitude: 19.54
    longitude: -155.58
    elevation: 3400.0
    utc_offset: -10.00 # Hours
    horizon: 30
    twilight_horizon: -12
    timezone: 'US/Hawaii'
directories:
    base: '/var/panoptes/POCS'
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
    resources: '/var/panoptes/POCS/resources/'
    targets: '/var/panoptes/POCS/resources/conf_files/targets'
    mounts: '/var/panoptes/POCS/resources/conf_files/mounts'
scheduler:
    type: 'core'
    targets_file: 'default_targets.yaml'
mount:
    brand: ioptron
    model: 30
    driver: ioptron
    port: '/dev/ttyUSB1'
    non_sidereal_available: True
pointing:
    threshold: 0.05
    exptime: 30
    max_iterations: 3
cameras:
    auto_detect: True
    devices:
    -
        model: canon_gphoto2
        primary: True
        guide: True
    -
        model: canon_gphoto2
messaging:
    port: 6500
state_machine: simple_state_table
