channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astroplan
  - astropy
  - docopt
  - fastapi
  - google-cloud-storage
  - google-cloud-firestore
  - gsutil
  - ipython
  - jupyterlab
  - matplotlib-base
  - numpy
  - pandas
  - pip
  - protobuf==4.23.0
  - pynacl
  - pyrsistent
  - streamz
  - typer[all]
  - uvicorn[standard]
  - pip:
      - -e ".[google,sensors]"
