[build-system]
requires = ["setuptools>=80.0.0", "setuptools_scm[toml]>=5", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"

[project]
name = "panoptes-pocs"
description = "PANOPTES Observatory Control System"
authors = [
    {name = "Project PANOPTES", email = "developers@projectpanoptes.org"},
]
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Astronomy",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "importlib-metadata; python_version<\"3.12\"",
    "astroplan",
    "astropy>=7.0",
    "astroquery",
    "certifi>=2023.7.22",
    "fastapi<0.106.0",
    "fastapi-utils",
    "human-readable",
    "numpy>=1.24",
    "panoptes-utils[config]>=0.2.47",
    "pandas",
    "pick",
    "Pillow>=10.0.1",
    "pyserial",
    "requests>=2.31.0",
    "scipy>=1.10.0",
    "scikit-image",
    "sparklines",
    "tqdm",
    "transitions",
    "typer[all]",
    "typing-inspect",
    "urllib3>=1.26.18",
    "uvicorn[standard]",
    "watchdog",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/panoptes/POCS"
Documentation = "https://panoptes-pocs.readthedocs.org"
Forum = "https://forum.projectpanoptes.org"

[project.optional-dependencies]
focuser = [
    "matplotlib",
    "scipy>=1.10.0",
]
google = [
    "google-cloud-firestore",
    "google-cloud-logging",
    "google-cloud-storage",
    "gsutil",
    "protobuf==4.23.0",
    "rsa",
]
testing = [
    "coverage",
    "pycodestyle",
    "pytest",
    "pytest-cov",
    "pytest-doctestplus",
    "pytest-remotedata>=0.3.1",
    "responses",
]
sensors = [
    "streamz",
]
weather = [
    "panoptes-aag",
]

[project.scripts]
pocs = "panoptes.pocs.utils.cli.main:app"

[tool.setuptools]
zip-safe = false
include-package-data = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]

[tool.pytest.ini_options]
addopts = [
    "--cov", "panoptes.pocs",
    "--cov", "tests",
    "--cov-branch",
    "--cov-report", "term-missing:skip-covered",
    "--cov-report", "xml:build/coverage.xml",
    "--no-cov-on-fail",
    "--doctest-modules",
    "--doctest-ignore-import-errors",
    "--doctest-modules",
    "-x",
    "-vv",
]
norecursedirs = [
    "docker",
    "script",
    "resources",
    "dist",
    "build",
    ".tox",
]
testpaths = ["tests", "src"]
doctest_optionflags = "ELLIPSIS NORMALIZE_WHITESPACE ALLOW_UNICODE IGNORE_EXCEPTION_DETAIL"
filterwarnings = [
    "ignore:elementwise == comparison failed:DeprecationWarning",
    "ignore::pytest.PytestDeprecationWarning",
]
doctest_plus = "enabled"
markers = [
    "theskyx",
    "without_camera",
    "with_camera",
    "without_mount",
    "with_mount",
    "without_sensors",
    "with_sensors",
    "plate_solve",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self\\.debug",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
]
ignore_errors = true

[tool.pycodestyle]
max-line-length = 100
