optics:
    canon: # Canon 2.8/400 lens
        aperture: 139.642857143 # millimetres
        focal_length: 391.0 # millimetres
        throughput_filename: 'resources/performance_data/canon_throughput.csv'
        central_obstruction: 0.0 #millimetres
        
    rasa: #Celestron RASA
        aperture: 279.0 # millimetres
        focal_length: 620.0 # millimetres
        throughput_filename: 'resources/performance_data/rasa_tau.csv'
        central_obstruction: 129.0 # millimetres

cameras:
    sbig: # STF-8300M
        bit_depth: 16
        full_well: 25500 # electrons
        gain: 0.37 # electron/u.adu
        readout_time: 2 # second
        pixel_size: 5.4 # micron / pixel
        resolution: 3326, 2504 # pixel
        read_noise: 9.3  # electron / pixel
        dark_current: 0.04 # electron / (second * pixel)
        QE_filename: 'resources/performance_data/ML8300M_QE.csv'
        minimum_exposure: 0.1 # second
        
    fli: # ML50100
        bit_depth: 16
        full_well: 40300 # electrons
        gain: 0.555 # electron/u.adu
        readout_time: 2 # second
        pixel_size: 6.0 # micron / pixel
        resolution: 8176, 6132 # pixel
        read_noise: 9.3  # electron / pixel
        dark_current: 0.04 # electron / (second * pixel)
        QE_filename: 'resources/performance_data/ML8300M_QE.csv'
        minimum_exposure: 0.1 # second
        
    zwo: # ASI1600MM
        bit_depth: 12
        full_well: 40300 # electrons
        gain: 0.555 # electron/u.adu
        readout_time: 2 # second
        pixel_size: 6.0 # micron / pixel
        resolution: 4656, 3520 # pixel
        read_noise: 3.65 # electron / pixel
        dark_current: 0.0086761766287033644 # electron / (second * pixel)
        QE_filename: 'resources/performance_data/ZWO_QE.csv'
        minimum_exposure: 0.000032 # second


filters:
    g':
        transmission_filename: 'resources/performance_data/astrodon_g.csv'
        sky_mu: 22.5
        
    r':
        transmission_filename: 'resources/performance_data/astrodon_r.csv'
        sky_mu: 21.5
    
    Ha_3nm:
        transmission_filename: 'resources/performance_data/astrodon_ha_3nm.csv'
        sky_mu: 20.5
        
    Ha_5nm:
        transmission_filename: 'resources/performance_data/astrodon_ha_5nm.csv'
        sky_mu: 20.5

psfs:
    2as:
        FWHM: 2 # arcsecond
        alpha: 2.5

imagers:
     -  name: canon_sbig_g
        optic: canon
        camera: sbig
        filter: g'
        psf: 2as
        num_imagers: 5
        num_computer: 5
       
     -  name: canon_sbig_r
        optic: canon
        camera: sbig
        filter: r'
        psf: 2as
        num_imagers: 5
        num_computer: 5
        
        
        