channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - astroplan
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab  # Interactive
  - jupyterlab_widgets
  - matplotlib-base
  - numpy
  - pandas
  - panel
  - photutils
  - pip
  - pyviz_comms
  - scipy
  - pip:
      - "git+https://github.com/panoptes/panoptes-utils@develop#egg=panoptes-utils[config,images,social]"
