channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - jupyterlab  # Interactive
  - matplotlib-base
  - numpy
  - photutils
  - pillow
  - pip
  - readline  # POCS shell
  - scipy
  - pip:
      - panoptes-utils[config] >= 0.2.30
